// Seeds initial workspaces, agents and sample data on first run.
import { repo } from './client';

let seeded = false;

export async function ensureSeed() {
  if (seeded) return;
  const wsRepo = repo('workspaces');
  const existing = await wsRepo.list();
  if (existing.length > 0) { seeded = true; return; }

  const seedWorkspaces = [
    { id: 'jef-moldova', name: 'JEF Moldova', slug: 'jef-moldova', emoji: '\ud83c\uddf2\ud83c\udde9', tagline: 'Young European Federalists — Moldova', color: 'from-brand-500 to-aurora-cyan' },
    { id: 'cntm', name: 'CNTM', slug: 'cntm', emoji: '\u2728', tagline: 'National Youth Council of Moldova', color: 'from-aurora-violet to-aurora-rose' },
    { id: 'ao-norda', name: 'AO Norda', slug: 'ao-norda', emoji: '\ud83c\udf2c\ufe0f', tagline: 'Northern Youth Development Association', color: 'from-aurora-mint to-aurora-amber' },
  ];
  for (const w of seedWorkspaces) await wsRepo.create(w);

  const projectRepo = repo('projects');
  await projectRepo.create({ workspaceId:'jef-moldova', name:'Youth4EU Civic Lab', status:'active', progress:62, members:8, description:'Civic education program for 200+ young Moldovans on EU integration.' });
  await projectRepo.create({ workspaceId:'jef-moldova', name:'Erasmus+ KA2 Partnership', status:'drafting', progress:25, members:5, description:'Multi-country partnership building digital skills curriculum.' });
  await projectRepo.create({ workspaceId:'cntm', name:'Youth Voice 2025', status:'active', progress:80, members:12, description:'National advocacy campaign on youth participation.' });
  await projectRepo.create({ workspaceId:'ao-norda', name:'Rural Innovators', status:'planning', progress:10, members:4, description:'Empowering rural youth with entrepreneurship training.' });

  const grantsRepo = repo('grants');
  await grantsRepo.create({ workspaceId:'jef-moldova', title:'Erasmus+ Youth Exchange — Climate Action', funder:'European Commission', amount:48000, currency:'EUR', deadline:'2025-09-15', status:'drafting', match:92 });
  await grantsRepo.create({ workspaceId:'cntm', title:'Council of Europe — Democracy Lab', funder:'Council of Europe', amount:25000, currency:'EUR', deadline:'2025-08-01', status:'submitted', match:88 });

  const oppsRepo = repo('opportunities');
  const opps = [
    { title:'Erasmus+ Training: Digital Storytelling for NGOs', org:'SALTO Youth', country:'Portugal', deadline:'2025-08-20', category:'Training', match:96 },
    { title:'European Youth Foundation Pilot Activity', org:'Council of Europe', country:'Online', deadline:'2025-09-01', category:'Grant', match:91 },
    { title:'EuroPeers Hackathon Civic Tech', org:'EuroPeers', country:'Germany', deadline:'2025-07-30', category:'Hackathon', match:87 },
    { title:'Volunteer with SCI — Climate Action Camp', org:'Service Civil International', country:'Italy', deadline:'2025-07-15', category:'Volunteering', match:82 },
    { title:'Youth Exchange: Bridges Across Borders', org:'JEF Europe', country:'Belgium', deadline:'2025-08-10', category:'Youth Exchange', match:94 },
  ];
  for (const o of opps) await oppsRepo.create({ workspaceId:'global', ...o });

  const agentsRepo = repo('agents');
  const agents = [
    { workspaceId:'global', key:'grant', name:'Grant Agent', emoji:'\ud83d\udcb8', tagline:'Drafts full grant proposals, budgets, and logframes.', system:'You are a senior NGO grant writer. Produce structured, fundable proposals.' },
    { workspaceId:'global', key:'presentation', name:'Presentation Agent', emoji:'\ud83c\udfa8', tagline:'Generates editable slide decks for events and donors.', system:'You are a deck designer for youth NGOs. Produce clear slide outlines with titles + bullets.' },
    { workspaceId:'global', key:'research', name:'Research Agent', emoji:'\ud83d\udd0e', tagline:'Synthesizes reports from documents and the web.', system:'You are a research analyst for civic-tech and youth policy.' },
    { workspaceId:'global', key:'social', name:'Social Media Agent', emoji:'\ud83d\udcf1', tagline:'Crafts campaigns across LinkedIn, IG, X and TikTok.', system:'You are a Gen-Z social strategist for youth NGOs.' },
    { workspaceId:'global', key:'opportunity', name:'Opportunity Agent', emoji:'\ud83c\udf1f', tagline:'Personalizes Erasmus+, grants and youth exchanges.', system:'You are an opportunity matcher for European youth programs.' },
  ];
  for (const a of agents) await agentsRepo.create(a);

  const actRepo = repo('activities');
  await actRepo.create({ workspaceId:'jef-moldova', type:'project.created', text:'Youth4EU Civic Lab project created', actor:'system' });
  await actRepo.create({ workspaceId:'jef-moldova', type:'grant.drafted', text:'Erasmus+ KA2 draft generated by Grant Agent', actor:'ai' });
  await actRepo.create({ workspaceId:'cntm', type:'doc.indexed', text:'Strategy_2025.pdf indexed in Knowledge', actor:'system' });

  seeded = true;
}
